//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoSubunidad
    {
        public int idContratoSubUnidad { get; set; }
        public int idContrato { get; set; }
        public int idSubunidad { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
