//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.ContratoSubunidad = new HashSet<ContratoSubunidad>();
        }
    
        public int id_contrato { get; set; }
        public string numero_contrato { get; set; }
        public int RepresentanteLegalId { get; set; }
        public string evidencia_pdf { get; set; }
        public Nullable<int> EscalaOcupacionalId { get; set; }
        public int Id_Persona { get; set; }
        public int id_subunidad { get; set; }
        public int idTipoContratoCargo { get; set; }
        public bool Eliminado { get; set; }
        public int GrupoGastosId { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> PeriodoFical { get; set; }
        public Nullable<bool> EstadoContrato { get; set; }
        public string partidaindividual { get; set; }
    
        public virtual EscalaOcupacional EscalaOcupacional { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual tipoContratoCargo tipoContratoCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoSubunidad> ContratoSubunidad { get; set; }
    }
}
