//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancaria
    {
        public int CuentaBancariaID { get; set; }
        public string NroCuenta { get; set; }
        public Nullable<int> BancoId { get; set; }
        public Nullable<int> TipoCuentaId { get; set; }
        public Nullable<int> Id_Persona { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TipoCuentaBancaria TipoCuentaBancaria { get; set; }
    }
}
