//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Descuento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        

        public int id_descuento { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<int> Id_Persona { get; set; }
        public Nullable<int> cab_desc_id { get; set; }
        public Nullable<int> mes_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> est_delete { get; set; }

        public virtual Cabecera_Descuento Cabecera_Descuento { get; set; }
        public virtual Mes Mes { get; set; }
    
}
}
