//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado_asociacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado_asociacion()
        {
            this.Credito = new HashSet<Credito>();
        }
    
        public int id_empl_aso { get; set; }
        public Nullable<int> Id_Persona { get; set; }
        public Nullable<int> asociacion_id { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<bool> est_delete { get; set; }
    
        public virtual Asociacion Asociacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credito> Credito { get; set; }
    }
}
