//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public int id_ingresos { get; set; }
        public double valor { get; set; }
        public Nullable<int> asociacion_id { get; set; }
        public Nullable<int> tipo_ingreso_id { get; set; }
        public Nullable<int> mes_id { get; set; }
        public Nullable<bool> est_delete { get; set; }
    
        public virtual Asociacion Asociacion { get; set; }
        public virtual Mes Mes { get; set; }
        public virtual Tipo_ingreso Tipo_ingreso { get; set; }
    }
}
