//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Roles_Creditos_BDEntities1 : DbContext
    {
        public Roles_Creditos_BDEntities1()
            : base("name=Roles_Creditos_BDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asociacion> Asociacion { get; set; }
        public virtual DbSet<Asociacion_Proveedor> Asociacion_Proveedor { get; set; }
        public virtual DbSet<Cabecera_Descuento> Cabecera_Descuento { get; set; }
        public virtual DbSet<Credito> Credito { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<Egresos> Egresos { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<empleado_asociacion> empleado_asociacion { get; set; }
        public virtual DbSet<info_financiera> info_financiera { get; set; }
        public virtual DbSet<Ingresos> Ingresos { get; set; }
        public virtual DbSet<Mes> Mes { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Sobrante> Sobrante { get; set; }
        public virtual DbSet<SubDescuento> SubDescuento { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_egreso> Tipo_egreso { get; set; }
        public virtual DbSet<Tipo_ingreso> Tipo_ingreso { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Valor_Asignado> Valor_Asignado { get; set; }
        public virtual DbSet<Valor_Utilizado> Valor_Utilizado { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<spConsultarAsociacion_Result> spConsultarAsociacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarAsociacion_Result>("spConsultarAsociacion");
        }
    
        public virtual ObjectResult<spConsultarAsociacionProveedor_Result> spConsultarAsociacionProveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarAsociacionProveedor_Result>("spConsultarAsociacionProveedor");
        }
    
        public virtual ObjectResult<spConsultarCabeceraDescuento_Result> spConsultarCabeceraDescuento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarCabeceraDescuento_Result>("spConsultarCabeceraDescuento");
        }
    
        public virtual ObjectResult<spConsultarCredito_Result> spConsultarCredito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarCredito_Result>("spConsultarCredito");
        }
    
        public virtual ObjectResult<spConsultarDescuento_Result> spConsultarDescuento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarDescuento_Result>("spConsultarDescuento");
        }
    
        public virtual ObjectResult<spConsultarEgreso_Result> spConsultarEgreso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarEgreso_Result>("spConsultarEgreso");
        }
    
        public virtual ObjectResult<spConsultarEmpleadoAsociacion_Result> spConsultarEmpleadoAsociacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarEmpleadoAsociacion_Result>("spConsultarEmpleadoAsociacion");
        }
    
        public virtual ObjectResult<spConsultarIngreso_Result> spConsultarIngreso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarIngreso_Result>("spConsultarIngreso");
        }
    
        public virtual ObjectResult<spConsultarMes_Result> spConsultarMes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarMes_Result>("spConsultarMes");
        }
    
        public virtual ObjectResult<spConsultarProveedor_Result> spConsultarProveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarProveedor_Result>("spConsultarProveedor");
        }
    
        public virtual ObjectResult<spConsultarSobrante_Result> spConsultarSobrante()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarSobrante_Result>("spConsultarSobrante");
        }
    
        public virtual ObjectResult<spConsultarSubDescuento_Result> spConsultarSubDescuento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarSubDescuento_Result>("spConsultarSubDescuento");
        }
    
        public virtual ObjectResult<spConsultarTipoEgreso_Result> spConsultarTipoEgreso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarTipoEgreso_Result>("spConsultarTipoEgreso");
        }
    
        public virtual ObjectResult<spConsultarTipoIngreso_Result> spConsultarTipoIngreso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarTipoIngreso_Result>("spConsultarTipoIngreso");
        }
    
        public virtual ObjectResult<spConsultarValorAsignado_Result> spConsultarValorAsignado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarValorAsignado_Result>("spConsultarValorAsignado");
        }
    
        public virtual ObjectResult<spConsultarValorUtilizado_Result> spConsultarValorUtilizado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarValorUtilizado_Result>("spConsultarValorUtilizado");
        }
    
        public virtual int spEliminarAsociacion(Nullable<int> id_asociacion)
        {
            var id_asociacionParameter = id_asociacion.HasValue ?
                new ObjectParameter("id_asociacion", id_asociacion) :
                new ObjectParameter("id_asociacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarAsociacion", id_asociacionParameter);
        }
    
        public virtual int spEliminarAsociacionProveedor(Nullable<int> id_asoc_prov)
        {
            var id_asoc_provParameter = id_asoc_prov.HasValue ?
                new ObjectParameter("id_asoc_prov", id_asoc_prov) :
                new ObjectParameter("id_asoc_prov", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarAsociacionProveedor", id_asoc_provParameter);
        }
    
        public virtual int spEliminarCabeceraDescuento(Nullable<int> id_cabecera_descuento)
        {
            var id_cabecera_descuentoParameter = id_cabecera_descuento.HasValue ?
                new ObjectParameter("id_cabecera_descuento", id_cabecera_descuento) :
                new ObjectParameter("id_cabecera_descuento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarCabeceraDescuento", id_cabecera_descuentoParameter);
        }
    
        public virtual int spEliminarCredito(Nullable<int> id_credito)
        {
            var id_creditoParameter = id_credito.HasValue ?
                new ObjectParameter("id_credito", id_credito) :
                new ObjectParameter("id_credito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarCredito", id_creditoParameter);
        }
    
        public virtual int spEliminarDescuento(Nullable<int> id_descuento)
        {
            var id_descuentoParameter = id_descuento.HasValue ?
                new ObjectParameter("id_descuento", id_descuento) :
                new ObjectParameter("id_descuento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarDescuento", id_descuentoParameter);
        }
    
        public virtual int spEliminarEgreso(Nullable<int> id_egresos)
        {
            var id_egresosParameter = id_egresos.HasValue ?
                new ObjectParameter("id_egresos", id_egresos) :
                new ObjectParameter("id_egresos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarEgreso", id_egresosParameter);
        }
    
        public virtual int spEliminarEmpleadoAsociacion(Nullable<int> id_empl_aso)
        {
            var id_empl_asoParameter = id_empl_aso.HasValue ?
                new ObjectParameter("id_empl_aso", id_empl_aso) :
                new ObjectParameter("id_empl_aso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarEmpleadoAsociacion", id_empl_asoParameter);
        }
    
        public virtual int spEliminarIngreso(Nullable<int> id_ingresos)
        {
            var id_ingresosParameter = id_ingresos.HasValue ?
                new ObjectParameter("id_ingresos", id_ingresos) :
                new ObjectParameter("id_ingresos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarIngreso", id_ingresosParameter);
        }
    
        public virtual int spEliminarMes(Nullable<int> id_mes)
        {
            var id_mesParameter = id_mes.HasValue ?
                new ObjectParameter("id_mes", id_mes) :
                new ObjectParameter("id_mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarMes", id_mesParameter);
        }
    
        public virtual int spEliminarProveedor(Nullable<int> id_proveedor)
        {
            var id_proveedorParameter = id_proveedor.HasValue ?
                new ObjectParameter("id_proveedor", id_proveedor) :
                new ObjectParameter("id_proveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarProveedor", id_proveedorParameter);
        }
    
        public virtual int spEliminarSobrante(Nullable<int> id_sobrante)
        {
            var id_sobranteParameter = id_sobrante.HasValue ?
                new ObjectParameter("id_sobrante", id_sobrante) :
                new ObjectParameter("id_sobrante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarSobrante", id_sobranteParameter);
        }
    
        public virtual int spEliminarSubDescuento(Nullable<int> id_subdescuento)
        {
            var id_subdescuentoParameter = id_subdescuento.HasValue ?
                new ObjectParameter("id_subdescuento", id_subdescuento) :
                new ObjectParameter("id_subdescuento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarSubDescuento", id_subdescuentoParameter);
        }
    
        public virtual int spEliminarTipoEgreso(Nullable<int> id_tipo_egreso)
        {
            var id_tipo_egresoParameter = id_tipo_egreso.HasValue ?
                new ObjectParameter("id_tipo_egreso", id_tipo_egreso) :
                new ObjectParameter("id_tipo_egreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarTipoEgreso", id_tipo_egresoParameter);
        }
    
        public virtual int spEliminarTipoIngreso(Nullable<int> id_tipo_ingreso)
        {
            var id_tipo_ingresoParameter = id_tipo_ingreso.HasValue ?
                new ObjectParameter("id_tipo_ingreso", id_tipo_ingreso) :
                new ObjectParameter("id_tipo_ingreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarTipoIngreso", id_tipo_ingresoParameter);
        }
    
        public virtual int spEliminarValorAsignado(Nullable<int> id_valor_asig)
        {
            var id_valor_asigParameter = id_valor_asig.HasValue ?
                new ObjectParameter("id_valor_asig", id_valor_asig) :
                new ObjectParameter("id_valor_asig", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarValorAsignado", id_valor_asigParameter);
        }
    
        public virtual int spEliminarValorUtilizado(Nullable<int> id_valor_usad)
        {
            var id_valor_usadParameter = id_valor_usad.HasValue ?
                new ObjectParameter("id_valor_usad", id_valor_usad) :
                new ObjectParameter("id_valor_usad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminarValorUtilizado", id_valor_usadParameter);
        }
    
        public virtual int spInsertarAsociacion(string descripcion, Nullable<bool> est_delete)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarAsociacion", descripcionParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarAsociacionProveedor(Nullable<int> proveedor_id, Nullable<int> asociacion_id, Nullable<System.DateTime> fecha, Nullable<bool> est_delete)
        {
            var proveedor_idParameter = proveedor_id.HasValue ?
                new ObjectParameter("proveedor_id", proveedor_id) :
                new ObjectParameter("proveedor_id", typeof(int));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarAsociacionProveedor", proveedor_idParameter, asociacion_idParameter, fechaParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarCabeceraDescuento(string descripcion, Nullable<int> subdescuento_id, Nullable<bool> est_delete)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var subdescuento_idParameter = subdescuento_id.HasValue ?
                new ObjectParameter("subdescuento_id", subdescuento_id) :
                new ObjectParameter("subdescuento_id", typeof(int));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarCabeceraDescuento", descripcionParameter, subdescuento_idParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarCredito(string descripcion, Nullable<double> cantidad, Nullable<System.DateTime> fecha_solicitud, Nullable<System.DateTime> fecha_aprobacion, Nullable<double> desc_mensual, Nullable<int> emp_aso_id, Nullable<int> numero_cuota, Nullable<bool> estado_activacion, Nullable<bool> estado_aprobacion, Nullable<bool> est_delete)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(double));
    
            var fecha_solicitudParameter = fecha_solicitud.HasValue ?
                new ObjectParameter("fecha_solicitud", fecha_solicitud) :
                new ObjectParameter("fecha_solicitud", typeof(System.DateTime));
    
            var fecha_aprobacionParameter = fecha_aprobacion.HasValue ?
                new ObjectParameter("fecha_aprobacion", fecha_aprobacion) :
                new ObjectParameter("fecha_aprobacion", typeof(System.DateTime));
    
            var desc_mensualParameter = desc_mensual.HasValue ?
                new ObjectParameter("desc_mensual", desc_mensual) :
                new ObjectParameter("desc_mensual", typeof(double));
    
            var emp_aso_idParameter = emp_aso_id.HasValue ?
                new ObjectParameter("emp_aso_id", emp_aso_id) :
                new ObjectParameter("emp_aso_id", typeof(int));
    
            var numero_cuotaParameter = numero_cuota.HasValue ?
                new ObjectParameter("numero_cuota", numero_cuota) :
                new ObjectParameter("numero_cuota", typeof(int));
    
            var estado_activacionParameter = estado_activacion.HasValue ?
                new ObjectParameter("estado_activacion", estado_activacion) :
                new ObjectParameter("estado_activacion", typeof(bool));
    
            var estado_aprobacionParameter = estado_aprobacion.HasValue ?
                new ObjectParameter("estado_aprobacion", estado_aprobacion) :
                new ObjectParameter("estado_aprobacion", typeof(bool));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarCredito", descripcionParameter, cantidadParameter, fecha_solicitudParameter, fecha_aprobacionParameter, desc_mensualParameter, emp_aso_idParameter, numero_cuotaParameter, estado_activacionParameter, estado_aprobacionParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarDescuento(Nullable<double> valor, Nullable<int> empleado_id, Nullable<int> cab_desc_id, Nullable<int> mes_id, Nullable<System.DateTime> fecha, Nullable<bool> est_delete)
        {
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var empleado_idParameter = empleado_id.HasValue ?
                new ObjectParameter("empleado_id", empleado_id) :
                new ObjectParameter("empleado_id", typeof(int));
    
            var cab_desc_idParameter = cab_desc_id.HasValue ?
                new ObjectParameter("cab_desc_id", cab_desc_id) :
                new ObjectParameter("cab_desc_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarDescuento", valorParameter, empleado_idParameter, cab_desc_idParameter, mes_idParameter, fechaParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarEgreso(Nullable<double> valor, Nullable<int> asociacion_id, Nullable<int> tipo_egreso_id, Nullable<int> mes_id, Nullable<bool> est_delete)
        {
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var tipo_egreso_idParameter = tipo_egreso_id.HasValue ?
                new ObjectParameter("tipo_egreso_id", tipo_egreso_id) :
                new ObjectParameter("tipo_egreso_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarEgreso", valorParameter, asociacion_idParameter, tipo_egreso_idParameter, mes_idParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarEmpleadoAsociacion(Nullable<int> empleado_id, Nullable<int> asociacion_id, Nullable<System.DateTime> fecha_ingreso, Nullable<bool> est_delete)
        {
            var empleado_idParameter = empleado_id.HasValue ?
                new ObjectParameter("empleado_id", empleado_id) :
                new ObjectParameter("empleado_id", typeof(int));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var fecha_ingresoParameter = fecha_ingreso.HasValue ?
                new ObjectParameter("fecha_ingreso", fecha_ingreso) :
                new ObjectParameter("fecha_ingreso", typeof(System.DateTime));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarEmpleadoAsociacion", empleado_idParameter, asociacion_idParameter, fecha_ingresoParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarIngreso(Nullable<double> valor, Nullable<int> asociacion_id, Nullable<int> tipo_ingreso_id, Nullable<int> mes_id, Nullable<bool> est_delete)
        {
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var tipo_ingreso_idParameter = tipo_ingreso_id.HasValue ?
                new ObjectParameter("tipo_ingreso_id", tipo_ingreso_id) :
                new ObjectParameter("tipo_ingreso_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarIngreso", valorParameter, asociacion_idParameter, tipo_ingreso_idParameter, mes_idParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarMes(string descripcion, Nullable<bool> est_delete)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarMes", descripcionParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarProveedor(string persona_juridica, string rUC, string nombre, string descripcion, string email, string direccion, string telefono, Nullable<bool> est_delete)
        {
            var persona_juridicaParameter = persona_juridica != null ?
                new ObjectParameter("persona_juridica", persona_juridica) :
                new ObjectParameter("persona_juridica", typeof(string));
    
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarProveedor", persona_juridicaParameter, rUCParameter, nombreParameter, descripcionParameter, emailParameter, direccionParameter, telefonoParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarSobrante(Nullable<int> descuento_id, Nullable<double> valor, Nullable<bool> estado, Nullable<bool> est_delete)
        {
            var descuento_idParameter = descuento_id.HasValue ?
                new ObjectParameter("descuento_id", descuento_id) :
                new ObjectParameter("descuento_id", typeof(int));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarSobrante", descuento_idParameter, valorParameter, estadoParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarSubDescuento(string descripcion, Nullable<bool> est_delete)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarSubDescuento", descripcionParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarTipoEgreso(string descripcion, Nullable<bool> est_delete)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarTipoEgreso", descripcionParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarTipoIngreso(string descripcion, Nullable<bool> est_delete)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarTipoIngreso", descripcionParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarValorAsignado(Nullable<int> proveedor_id, Nullable<int> aso_id, Nullable<int> empleado_id, Nullable<double> monto_aprobado, Nullable<bool> est_delete)
        {
            var proveedor_idParameter = proveedor_id.HasValue ?
                new ObjectParameter("proveedor_id", proveedor_id) :
                new ObjectParameter("proveedor_id", typeof(int));
    
            var aso_idParameter = aso_id.HasValue ?
                new ObjectParameter("aso_id", aso_id) :
                new ObjectParameter("aso_id", typeof(int));
    
            var empleado_idParameter = empleado_id.HasValue ?
                new ObjectParameter("empleado_id", empleado_id) :
                new ObjectParameter("empleado_id", typeof(int));
    
            var monto_aprobadoParameter = monto_aprobado.HasValue ?
                new ObjectParameter("monto_aprobado", monto_aprobado) :
                new ObjectParameter("monto_aprobado", typeof(double));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarValorAsignado", proveedor_idParameter, aso_idParameter, empleado_idParameter, monto_aprobadoParameter, est_deleteParameter);
        }
    
        public virtual int spInsertarValorUtilizado(Nullable<int> valor_asig_id, Nullable<int> mes_id, Nullable<double> cantidad_usada, Nullable<bool> est_delete)
        {
            var valor_asig_idParameter = valor_asig_id.HasValue ?
                new ObjectParameter("valor_asig_id", valor_asig_id) :
                new ObjectParameter("valor_asig_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            var cantidad_usadaParameter = cantidad_usada.HasValue ?
                new ObjectParameter("cantidad_usada", cantidad_usada) :
                new ObjectParameter("cantidad_usada", typeof(double));
    
            var est_deleteParameter = est_delete.HasValue ?
                new ObjectParameter("est_delete", est_delete) :
                new ObjectParameter("est_delete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarValorUtilizado", valor_asig_idParameter, mes_idParameter, cantidad_usadaParameter, est_deleteParameter);
        }
    
        public virtual int spModificarAsociacion(Nullable<int> id_asociacion, string descripcion)
        {
            var id_asociacionParameter = id_asociacion.HasValue ?
                new ObjectParameter("id_asociacion", id_asociacion) :
                new ObjectParameter("id_asociacion", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarAsociacion", id_asociacionParameter, descripcionParameter);
        }
    
        public virtual int spModificarAsociacionProveedor(Nullable<int> id_asoc_prov, Nullable<int> proveedor_id, Nullable<int> asociacion_id, Nullable<System.DateTime> fecha)
        {
            var id_asoc_provParameter = id_asoc_prov.HasValue ?
                new ObjectParameter("id_asoc_prov", id_asoc_prov) :
                new ObjectParameter("id_asoc_prov", typeof(int));
    
            var proveedor_idParameter = proveedor_id.HasValue ?
                new ObjectParameter("proveedor_id", proveedor_id) :
                new ObjectParameter("proveedor_id", typeof(int));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarAsociacionProveedor", id_asoc_provParameter, proveedor_idParameter, asociacion_idParameter, fechaParameter);
        }
    
        public virtual int spModificarCabeceraDescuento(Nullable<int> id_cabecera_descuento, string descripcion, Nullable<int> subdescuento_id)
        {
            var id_cabecera_descuentoParameter = id_cabecera_descuento.HasValue ?
                new ObjectParameter("id_cabecera_descuento", id_cabecera_descuento) :
                new ObjectParameter("id_cabecera_descuento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var subdescuento_idParameter = subdescuento_id.HasValue ?
                new ObjectParameter("subdescuento_id", subdescuento_id) :
                new ObjectParameter("subdescuento_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarCabeceraDescuento", id_cabecera_descuentoParameter, descripcionParameter, subdescuento_idParameter);
        }
    
        public virtual int spModificarCredito(Nullable<int> id_credito, string descripcion, Nullable<double> cantidad, Nullable<System.DateTime> fecha_solicitud, Nullable<System.DateTime> fecha_aprobacion, Nullable<double> desc_mensual, Nullable<int> emp_aso_id, Nullable<int> numero_cuota, Nullable<bool> estado_activacion, Nullable<bool> estado_aprobacion)
        {
            var id_creditoParameter = id_credito.HasValue ?
                new ObjectParameter("id_credito", id_credito) :
                new ObjectParameter("id_credito", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(double));
    
            var fecha_solicitudParameter = fecha_solicitud.HasValue ?
                new ObjectParameter("fecha_solicitud", fecha_solicitud) :
                new ObjectParameter("fecha_solicitud", typeof(System.DateTime));
    
            var fecha_aprobacionParameter = fecha_aprobacion.HasValue ?
                new ObjectParameter("fecha_aprobacion", fecha_aprobacion) :
                new ObjectParameter("fecha_aprobacion", typeof(System.DateTime));
    
            var desc_mensualParameter = desc_mensual.HasValue ?
                new ObjectParameter("desc_mensual", desc_mensual) :
                new ObjectParameter("desc_mensual", typeof(double));
    
            var emp_aso_idParameter = emp_aso_id.HasValue ?
                new ObjectParameter("emp_aso_id", emp_aso_id) :
                new ObjectParameter("emp_aso_id", typeof(int));
    
            var numero_cuotaParameter = numero_cuota.HasValue ?
                new ObjectParameter("numero_cuota", numero_cuota) :
                new ObjectParameter("numero_cuota", typeof(int));
    
            var estado_activacionParameter = estado_activacion.HasValue ?
                new ObjectParameter("estado_activacion", estado_activacion) :
                new ObjectParameter("estado_activacion", typeof(bool));
    
            var estado_aprobacionParameter = estado_aprobacion.HasValue ?
                new ObjectParameter("estado_aprobacion", estado_aprobacion) :
                new ObjectParameter("estado_aprobacion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarCredito", id_creditoParameter, descripcionParameter, cantidadParameter, fecha_solicitudParameter, fecha_aprobacionParameter, desc_mensualParameter, emp_aso_idParameter, numero_cuotaParameter, estado_activacionParameter, estado_aprobacionParameter);
        }
    
        public virtual int spModificarDescuento(Nullable<int> id_descuento, Nullable<double> valor, Nullable<int> empleado_id, Nullable<int> cab_desc_id, Nullable<int> mes_id, Nullable<System.DateTime> fecha)
        {
            var id_descuentoParameter = id_descuento.HasValue ?
                new ObjectParameter("id_descuento", id_descuento) :
                new ObjectParameter("id_descuento", typeof(int));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var empleado_idParameter = empleado_id.HasValue ?
                new ObjectParameter("empleado_id", empleado_id) :
                new ObjectParameter("empleado_id", typeof(int));
    
            var cab_desc_idParameter = cab_desc_id.HasValue ?
                new ObjectParameter("cab_desc_id", cab_desc_id) :
                new ObjectParameter("cab_desc_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarDescuento", id_descuentoParameter, valorParameter, empleado_idParameter, cab_desc_idParameter, mes_idParameter, fechaParameter);
        }
    
        public virtual int spModificarEgreso(Nullable<int> id_egresos, Nullable<double> valor, Nullable<int> asociacion_id, Nullable<int> tipo_egreso_id, Nullable<int> mes_id)
        {
            var id_egresosParameter = id_egresos.HasValue ?
                new ObjectParameter("id_egresos", id_egresos) :
                new ObjectParameter("id_egresos", typeof(int));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var tipo_egreso_idParameter = tipo_egreso_id.HasValue ?
                new ObjectParameter("tipo_egreso_id", tipo_egreso_id) :
                new ObjectParameter("tipo_egreso_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarEgreso", id_egresosParameter, valorParameter, asociacion_idParameter, tipo_egreso_idParameter, mes_idParameter);
        }
    
        public virtual int spModificarEmpleadoAsociacion(Nullable<int> id_empl_aso, Nullable<int> empleado_id, Nullable<int> asociacion_id, Nullable<System.DateTime> fecha_ingreso)
        {
            var id_empl_asoParameter = id_empl_aso.HasValue ?
                new ObjectParameter("id_empl_aso", id_empl_aso) :
                new ObjectParameter("id_empl_aso", typeof(int));
    
            var empleado_idParameter = empleado_id.HasValue ?
                new ObjectParameter("empleado_id", empleado_id) :
                new ObjectParameter("empleado_id", typeof(int));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var fecha_ingresoParameter = fecha_ingreso.HasValue ?
                new ObjectParameter("fecha_ingreso", fecha_ingreso) :
                new ObjectParameter("fecha_ingreso", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarEmpleadoAsociacion", id_empl_asoParameter, empleado_idParameter, asociacion_idParameter, fecha_ingresoParameter);
        }
    
        public virtual int spModificarIngreso(Nullable<int> id_ingresos, Nullable<double> valor, Nullable<int> asociacion_id, Nullable<int> tipo_ingreso_id, Nullable<int> mes_id)
        {
            var id_ingresosParameter = id_ingresos.HasValue ?
                new ObjectParameter("id_ingresos", id_ingresos) :
                new ObjectParameter("id_ingresos", typeof(int));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var asociacion_idParameter = asociacion_id.HasValue ?
                new ObjectParameter("asociacion_id", asociacion_id) :
                new ObjectParameter("asociacion_id", typeof(int));
    
            var tipo_ingreso_idParameter = tipo_ingreso_id.HasValue ?
                new ObjectParameter("tipo_ingreso_id", tipo_ingreso_id) :
                new ObjectParameter("tipo_ingreso_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarIngreso", id_ingresosParameter, valorParameter, asociacion_idParameter, tipo_ingreso_idParameter, mes_idParameter);
        }
    
        public virtual int spModificarMes(Nullable<int> id_mes, string descripcion)
        {
            var id_mesParameter = id_mes.HasValue ?
                new ObjectParameter("id_mes", id_mes) :
                new ObjectParameter("id_mes", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarMes", id_mesParameter, descripcionParameter);
        }
    
        public virtual int spModificarProveedor(Nullable<int> id_proveedor, string persona_juridica, string rUC, string nombre, string descripcion, string email, string direccion, string telefono)
        {
            var id_proveedorParameter = id_proveedor.HasValue ?
                new ObjectParameter("id_proveedor", id_proveedor) :
                new ObjectParameter("id_proveedor", typeof(int));
    
            var persona_juridicaParameter = persona_juridica != null ?
                new ObjectParameter("persona_juridica", persona_juridica) :
                new ObjectParameter("persona_juridica", typeof(string));
    
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarProveedor", id_proveedorParameter, persona_juridicaParameter, rUCParameter, nombreParameter, descripcionParameter, emailParameter, direccionParameter, telefonoParameter);
        }
    
        public virtual int spModificarSobrante(Nullable<int> id_sobrante, Nullable<int> descuento_id, Nullable<double> valor, Nullable<bool> estado)
        {
            var id_sobranteParameter = id_sobrante.HasValue ?
                new ObjectParameter("id_sobrante", id_sobrante) :
                new ObjectParameter("id_sobrante", typeof(int));
    
            var descuento_idParameter = descuento_id.HasValue ?
                new ObjectParameter("descuento_id", descuento_id) :
                new ObjectParameter("descuento_id", typeof(int));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarSobrante", id_sobranteParameter, descuento_idParameter, valorParameter, estadoParameter);
        }
    
        public virtual int spModificarSubDescuento(Nullable<int> id_subdescuento, string descripcion)
        {
            var id_subdescuentoParameter = id_subdescuento.HasValue ?
                new ObjectParameter("id_subdescuento", id_subdescuento) :
                new ObjectParameter("id_subdescuento", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarSubDescuento", id_subdescuentoParameter, descripcionParameter);
        }
    
        public virtual int spModificarTipoEgreso(Nullable<int> id_tipo_egreso, string descripcion)
        {
            var id_tipo_egresoParameter = id_tipo_egreso.HasValue ?
                new ObjectParameter("id_tipo_egreso", id_tipo_egreso) :
                new ObjectParameter("id_tipo_egreso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarTipoEgreso", id_tipo_egresoParameter, descripcionParameter);
        }
    
        public virtual int spModificarTipoIngreso(Nullable<int> id_tipo_ingreso, string descripcion)
        {
            var id_tipo_ingresoParameter = id_tipo_ingreso.HasValue ?
                new ObjectParameter("id_tipo_ingreso", id_tipo_ingreso) :
                new ObjectParameter("id_tipo_ingreso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarTipoIngreso", id_tipo_ingresoParameter, descripcionParameter);
        }
    
        public virtual int spModificarValorAsignado(Nullable<int> id_valor_asig, Nullable<int> proveedor_id, Nullable<int> aso_id, Nullable<int> empleado_id, Nullable<double> monto_aprobado)
        {
            var id_valor_asigParameter = id_valor_asig.HasValue ?
                new ObjectParameter("id_valor_asig", id_valor_asig) :
                new ObjectParameter("id_valor_asig", typeof(int));
    
            var proveedor_idParameter = proveedor_id.HasValue ?
                new ObjectParameter("proveedor_id", proveedor_id) :
                new ObjectParameter("proveedor_id", typeof(int));
    
            var aso_idParameter = aso_id.HasValue ?
                new ObjectParameter("aso_id", aso_id) :
                new ObjectParameter("aso_id", typeof(int));
    
            var empleado_idParameter = empleado_id.HasValue ?
                new ObjectParameter("empleado_id", empleado_id) :
                new ObjectParameter("empleado_id", typeof(int));
    
            var monto_aprobadoParameter = monto_aprobado.HasValue ?
                new ObjectParameter("monto_aprobado", monto_aprobado) :
                new ObjectParameter("monto_aprobado", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarValorAsignado", id_valor_asigParameter, proveedor_idParameter, aso_idParameter, empleado_idParameter, monto_aprobadoParameter);
        }
    
        public virtual int spModificarValorUtilizado(Nullable<int> id_valor_usad, Nullable<int> valor_asig_id, Nullable<int> mes_id, Nullable<double> cantidad_usada)
        {
            var id_valor_usadParameter = id_valor_usad.HasValue ?
                new ObjectParameter("id_valor_usad", id_valor_usad) :
                new ObjectParameter("id_valor_usad", typeof(int));
    
            var valor_asig_idParameter = valor_asig_id.HasValue ?
                new ObjectParameter("valor_asig_id", valor_asig_id) :
                new ObjectParameter("valor_asig_id", typeof(int));
    
            var mes_idParameter = mes_id.HasValue ?
                new ObjectParameter("mes_id", mes_id) :
                new ObjectParameter("mes_id", typeof(int));
    
            var cantidad_usadaParameter = cantidad_usada.HasValue ?
                new ObjectParameter("cantidad_usada", cantidad_usada) :
                new ObjectParameter("cantidad_usada", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spModificarValorUtilizado", id_valor_usadParameter, valor_asig_idParameter, mes_idParameter, cantidad_usadaParameter);
        }
    }
}
