//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sueldo()
        {
            this.tipoContratoCargo = new HashSet<tipoContratoCargo>();
        }
    
        public int SueldoId { get; set; }
        public string PartidaIndividual { get; set; }
        public Nullable<decimal> SueldoNumero { get; set; }
        public string SueldoLetras { get; set; }
        public Nullable<int> IdPartidaPresupuestaria { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipoContratoCargo> tipoContratoCargo { get; set; }
    }
}
