//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarioTipo
    {
        public int idTipoUsuario { get; set; }
        public int Id_Usuario { get; set; }
        public int idTipo { get; set; }
        public Nullable<bool> eliminado { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
