//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.usuarioTipo = new HashSet<usuarioTipo>();
        }
    
        public int Id_Usuario { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public Nullable<int> Id_Persona { get; set; }
        public string Foto { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioTipo> usuarioTipo { get; set; }
    }
}
