//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor_Utilizado
    {
        public int id_valor_usad { get; set; }
        public Nullable<int> valor_asig_id { get; set; }
        public Nullable<int> mes_id { get; set; }
        public Nullable<double> cantidad_usada { get; set; }
        public Nullable<bool> est_delete { get; set; }
    
        public virtual Mes Mes { get; set; }
        public virtual Valor_Asignado Valor_Asignado { get; set; }
    }
}
