//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creditos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valor_Asignado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Valor_Asignado()
        {
            this.Valor_Utilizado = new HashSet<Valor_Utilizado>();
        }
    
        public int id_valor_asig { get; set; }
        public Nullable<int> proveedor_id { get; set; }
        public Nullable<int> aso_id { get; set; }
        public Nullable<int> empleado_id { get; set; }
        public Nullable<double> monto_aprobado { get; set; }
        public Nullable<bool> est_delete { get; set; }
    
        public virtual Asociacion Asociacion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valor_Utilizado> Valor_Utilizado { get; set; }
    }
}
